package controller.commands;

/**
 * Created by jordi on 2/20/2017.
 */
public enum CommandType {
    END_TURN,
    CYCLE_MODE_NEXT,
    CYCLE_MODE_PREV,
    CYCLE_TYPE_NEXT,
    CYCLE_TYPE_PREV,
    CYCLE_INSTANCE_NEXT,
    CYCLE_INSTANCE_PREV,
    CYCLE_COMMAND_NEXT,
    CYCLE_COMMAND_PREV,
    SELECT,
    MOVE_CURSOR_NORTH,
    MOVE_CURSOR_SOUTH,
    MOVE_CURSOR_NORTH_EAST,
    MOVE_CURSOR_NORTH_WEST,
    MOVE_CURSOR_SOUTH_EAST,
    MOVE_CURSOR_SOUTH_WEST,
    MOVE,
    DECOMMISSION,
    DEFEND, EXPLORE, JOIN_ARMY, ADVANCE_TO_RALLY_POINT, ABANDON_ARMY, CANCEL_QUEUE, POWER_DOWN, POWER_UP, DISBAND, ATTACK,
    CREATE_UNIT, HEAL_UNIT, BUILD_STRUCTURE, BUILD_CAPITAL, PROSPECT,
    MOVE_CAMERA_UP, MOVE_CAMERA_DOWN, MOVE_CAMERA_LEFT, MOVE_CAMERA_RIGHT
}
